name: TByd UPM测试流水线

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: 运行测试 - Unity ${{ matrix.unity-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity-version: ['2021.3.8f1', '2022.3.10f1']
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 缓存Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.unity-version }}
          restore-keys: |
            Library-
      
      - name: Unity测试运行器
        uses: game-ci/unity-test-runner@v3
        with:
          unityVersion: ${{ matrix.unity-version }}
          testMode: all
          coverageOptions: 'generateBadgeReport;generateHtmlReport;generateBadge'
          customParameters: '-nographics'
      
      - name: 上传测试结果
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results-${{ matrix.unity-version }}
          path: artifacts/test-results
      
      - name: 上传覆盖率报告
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-Report-${{ matrix.unity-version }}
          path: artifacts/coverage
  
  performance:
    name: 性能基准测试
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 缓存Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Performance
          restore-keys: |
            Library-
      
      - name: Unity性能测试
        uses: game-ci/unity-test-runner@v3
        with:
          unityVersion: '2021.3.8f1'
          testMode: playmode
          customParameters: '-nographics -runTests -testCategory=Performance'
      
      - name: 上传性能测试结果
        uses: actions/upload-artifact@v3
        with:
          name: Performance-Results
          path: artifacts/performance-results
  
  build-package:
    name: 构建UPM包
    runs-on: ubuntu-latest
    needs: [test, performance]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 获取版本
        id: get-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      
      - name: 设置Node环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: 安装依赖
        run: |
          npm install -g npm-pack-all
      
      - name: 构建UPM包
        run: |
          npm-pack-all --output upm-package
      
      - name: 上传UPM包
        uses: actions/upload-artifact@v3
        with:
          name: upm-package-${{ steps.get-version.outputs.prop }}
          path: upm-package
      
      - name: 创建Release (仅限main分支)
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.prop }}
          name: Release v${{ steps.get-version.outputs.prop }}
          files: upm-package/*.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 